# This configuration file is a template.
# Copy it to "/etc/fs2es-indexer/config.yml" and tweak it!
# The commented values are exemplary, the uncommented values are the default values!


# The directories which should be indexed
directories:
#  - "/my-storage-directory"

# (Optional) Exclude directories / files from the index
#exclusions:
  # Exclusion via a simple string search in the full path of the file / directory.
  # If any of the given strings are found in the full path, it wont be added to the index.
  # Usually faster than a regular expression!
#  partial_paths:
#    - ".DS_Store"
#    - "._.DS_Store"

  # Exclusion via testing if a regular expression matches the full path of the file / directory.
  # If any of the regular expression matches, it wont be added to the index.
  # Usually slower than using a simple string search.
#  regular_expressions:
#    - "\.Trash-\d+"

elasticsearch:
  # The URL of the elasticsearch index
  url: "http://localhost:9200"

  # See the README.md for more information on how to setup user authentication
  # (Optional): The user for elasticsearch
#  user: "fs2es-indexer"

  # (Optional): The password for elasticsearch
#  password: "secret!"

  # The name of the elasticsearch index
  index: "files"

  # The amount of records to insert in one go (bulk)
  bulk_size: 10000

  # Verify the SSL certificate presented by the server (only if use_ssl == True)
  verify_certs: True

  # ElasticSearch would show a warning if use_ssl == True and verify_certs == False
  # This can be disabled here in order to keep the logs clean.
  ssl_show_warn: True

  # The path to the file containing all valid CA certificates
  # Shouldnt be necessary because "certifi" will be installed as a dependency
  #ca_certs: '/etc/ssl/certs/ca-certificates.crt'

  # The version of the elasticsearch-library
  # V8 has some pretty big changes, so we need to switch some statements.
  # Only change this if you dont use the installation via setup.py because there is a hardcoded dependency to v8!
  # Only v7 and v8 are valid.
  library_version: 8

  # The file where the mapping for the ElasticSearch index is saved.
  index_mapping: "/etc/fs2es-indexer/es-index-mapping.json"

# The wait time between indexing runs
# Allowed suffixes: s (seconds), m (minutes), h (hours), d (days)
wait_time: "30m"

# Do you want to the dump raw documents json to /tmp/fs2es-indexer-failed-documents-%date%.json
# in case it cant be indexed by elasticsearch?
dump_documents_on_error: False